### ISSUE TITLE
REI recipe autocomplete does not work.

### ISSUE THREAD

**Issue by Skreperiukas** [CyclopsMC/IntegratedTerminals#114]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When trying to to use REI recipe autocomplete items from system don't autocomplete.

#### Steps to reproduce the problem:

1. Have REI (Roughly Enough Items)
2. Open storage terminal.
3. Have all items for the item you want to craft.
4. Open recipe from recipe tab.
5. Press `+` button next to recipe output.
6. Autocomplete does not work.

#### Expected behaviour:
Crafting grid should be autocompleted with the recipe you pressed `+` on.

____

#### Versions:

- This mod: 1.4.12
- Minecraft: 1.20.1
- Forge: 47.2.0

#### Log file:
none

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This mod aims to support JEI, with REI just coming for free since it complies with the JEI API.
Does JEI work correctly on your end? If so, then it's probably an issue with REI not adhering to the JEI API, in which case it might be better to report this issue to the REI devs.

Which machine and recipe are you having issues with btw?

**Comment by Skreperiukas** [comment]
JEI works completely like it should.

I am not sure I understand what you mean by machine and recipe?
If what recipies don't autocomplete then all of them.

**Comment by rubensworks** [comment]
Ok, then it's probably an issue on REI's end.
Could you report this to the REI issue tracker, and link back here?
