### ISSUE TITLE
drawer as item interface causes max items to become max int

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTerminals#52]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. attach a storage drawer to the network with an item interface

#### Expected behaviour:

for the drawer's single stack to be read as it's max size
____

#### Versions:

- This mod: 1.0.13
- Minecraft: 1.12.2
- Forge: 8.0.99.99
![image](https://user-images.githubusercontent.com/21179158/80264238-1aea5e80-8659-11ea-8a9b-498bbb30c0ec.png)

**Comment by rubensworks** [comment]
Did you use any special configurations in your drawer?

I suspect the drawers are effectively exposing their max item count as max int.

**Comment by antrobot1234** [comment]
i didn't have anything special with my drawers

**Comment by rubensworks** [comment]
This seems to be caused by the way how drawers implements its capabilities:
https://github.com/jaquadro/StorageDrawers/blob/1.12/src/com/jaquadro/minecraft/storagedrawers/capabilities/DrawerItemHandler.java#L134-L135

I would suggest opening an issue on their issue tracker. Feel free to link back to here.

<blockquote><img src="https://avatars2.githubusercontent.com/u/852988?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jaquadro/StorageDrawers">jaquadro/StorageDrawers</a></strong></div><div>A mod adding compartmental storage for Minecraft Forge - jaquadro/StorageDrawers</div></blockquote>
