### ISSUE TITLE
1.16 multiplayer issues with JEI autofill failing in terminal crafting grid

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/IntegratedTerminals#74]
#### Issue type:

- :bug: Bug

____

#### Short description:

In multiplayer, attempting to populate a terminal's crafting grid using JEI auto-fill:
- ~~_at best_ fails with a server-logged non-halting error~~fixed as of 1.2.8, apparently
- _at worst_ disconnects the client with a payload size error (victim was using a portable storage terminal)

Issue has been reported infrequently in the Discord and little context has been given with each report.

One user reported that there was no such issue in singleplayer.
____

#### Versions:

Versions listed come from a user who reported being disconnected from the server.

Integrated Dynamics: `1.16.5-1.10.3`
IntegratedTerminals: `1.16.5-1.2.8`
JEI: `1.16.5-7.7.1.126`

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by GreyMario** [comment]
[10/31 report of user disconnected due to payload size.](https://discord.com/channels/386052815128100865/386054223688630272/904362869934678066) Ongoing as of now, may acquire additional replication information.

**Comment by GreyMario** [comment]
[10/18 report of silent failure of autofill, though we never got a server log from the user.](https://discord.com/channels/386052815128100865/386054223688630272/899793595958198302)

IntegratedTerminals `1.16.5-1.2.7`
IntegratedDynamics `1.16.5-1.10.2`
IntegratedTunnels `1.16.5-1.8.6`
CyclopsCore `1.16.5-1.11.10`

No JEI version was provided.

**Comment by rubensworks** [comment]
Could you share some more information about what recipe(s) cause the problem?

And do any stacktraces show up in the server logs?

**Comment by GreyMario** [comment]
```13.10 23:20:02 [Server] Server thread/FATAL [minecraft/ThreadTaskExecutor]: Error executing task on Server
13.10 23:20:02 [Server] INFO java.lang.NullPointerException: null
13.10 23:20:02 [Server] INFO at org.cyclops.integratedterminalscompat.modcompat.jei.JEIIntegratedTerminalsConfig.getItemStackMatchCondition(JEIIntegratedTerminalsConfig.java:56) ~[integratedterminals:1.2.7] {re:classloading}
13.10 23:20:02 [Server] INFO at org.cyclops.integratedterminalscompat.network.packet.TerminalStorageIngredientItemStackCraftingGridSetRecipe.actionServer(TerminalStorageIngredientItemStackCraftingGridSetRecipe.java:107) ~[integratedterminals:1.2.7] {re:classloading,pl:runtimedistcleaner:A}
13.10 23:20:02 [Server] INFO at org.cyclops.cyclopscore.network.PacketHandler.handlePacketServer(PacketHandler.java:101) ~[cyclopscore:1.11.10] {re:classloading,pl:runtimedistcleaner:A}
13.10 23:20:02 [Server] INFO at org.cyclops.cyclopscore.network.PacketHandler.lambda$null$4(PacketHandler.java:84) ~[cyclopscore:1.11.10] {re:classloading,pl:runtimedistcleaner:A}
```

Server log snippet from [10/13 report of this problem](https://discord.com/channels/386052815128100865/386054223688630272/898048133718761512), which does not have a JEI version included. [Rest of the Pastebin the user provided.](https://pastebin.com/7WWdigdh)

IntegratedTerminals `1.2.7`
CyclopsCore `1.11.10`


> Could you share some more information about what recipe(s) cause the problem?

Don't have that kind of info yet. It's like pulling teeth sometimes. It's likely this thread will just catch piecemeal information until someone slips up and accidentally mentions a modpack where this occurs...

**Comment by rubensworks** [comment]
> Server log snippet from 10/13 report of this problem, which does not have a JEI version included. Rest of the Pastebin the user provided.

That's already fixed in the 1.2.8 version.
It looks like the payload problem you're hinting at may still remain.

**Comment by GreyMario** [comment]
> That's already fixed in the 1.2.8 version.

Noted. ~~Watch as I forget in the next five minutes.~~

**Comment by fajcyk** [comment]
Hello, I'm having the same issue with payload error so I will try to provide as much info as is needed.

Modpack I'm playing is Enigmatica 6 (version 0.5.16 but with modifications).
First of all, this is only happening in multiplayer.
Also I had to modify modpack because of the other issue that got mentioned that got fixed in 1.28.

So modifications I made to the modpack are:
- IntegratedTerminals 1.16.5-1.2.7 -> IntegratedTerminals 1.16.5-1.2.8
- IntegratedDynamics 1.16.5-1.10.2 -> IntegratedDynamics 1.16.5-1.10.3
- IntegratedTunnels 1.16.5-1.8.6 -> IntegratedTunnels 1.16.5-1.8.7
- CyclopsCore 1.16.5-1.11.10 -> CyclopsCore 1.16.5-1.12.0
- JEI 7.7.1.126 -> JEI 7.7.1.129 (to fix broken config in-game as mentioned here https://github.com/mezz/JustEnoughItems/issues/2533)
- FTB Chunks 1605.3.2-build.65 -> FTB Chunks 1605.3.2-build.73 (to fix their performance issue, should be irrelevant)

No other changes have been made.
Example of a recipe where it happens would be regular piston.

When clicking on the '+' in JEI, client gets disconnected from the server with this message:

![error](https://user-images.githubusercontent.com/48088075/139670864-b730ae9d-0be6-42fa-8cf7-f7c45f8fbd37.png)

Here is part of latest.log from the client from the moment of joining the server to the kick:
https://pastebin.com/5X6C5dMW

Here is part of latest.log from the server from the moment of joining to the kick:
https://pastebin.com/pDidM9RG

Side note:
I was unable to replicate this issue on a clean minecraft installation with only:
- IntegratedTerminals 1.16.5-1.2.8
- IntegratedDynamics 1.16.5-1.10.3
- IntegratedTunnels 1.16.5-1.8.7
- CyclopsCore 1.16.5-1.12.0
- JEI 7.7.1.129
- CommonCapabilities 1.16.5-2.8.0 

so I guess the modpack has something to it (probably amount of possible replacements to cobblestone/planks in the recipe).

If any additional info is needed I will be happy to help, you can also find me on your discord with the same nick if needed.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/5X6C5dMW">[01Nov2021 13:25:52.311] [Render thread/INFO] [net.minecraft.client.gui.screen.C - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/pDidM9RG">[01Nov2021 12:25:51.727] [Netty Epoll Server IO #3/INFO] [codechicken.lib.config - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rubensworks** [comment]
Thanks for the additional details!

Note to self: Probably an issue with recipes that have many tag matches. Try to encode the packet more efficiently, so we don't exceed the threshold.

**Comment by fajcyk** [comment]
One more thing, I don't know if that's relevant to the issue, I tried messing with this config option in integratedterminals-common.toml :
```
#The maximum number of terminal storage instances that can be sent in a single packet. Reduce this when you have packet overflows.
terminalStoragePacketMaxInstances = 1024
```
by changing it to 256 and 64, but it didn't help.
