### ISSUE TITLE
Unable to take item out of terminal

### ISSUE THREAD

**Issue by kirjorjos** [CyclopsMC/IntegratedTerminals#83]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. ...Obtain one of the bugged items.

2. Put bugged item into terminal with any inventory attached

3. Attempt to take bugged item out of terminal.

#### Expected behaviour:

I expect it to enter my inventory like any other item.
____

#### Versions:

- This mod: 1.12.3
- Minecraft: 1.16.5
- Forge: 36.2.34

#### Log file:
[latest.log](https://github.com/CyclopsMC/IntegratedTerminals/files/9420859/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by met4000** [comment]
from [a message on the discord](https://discord.com/channels/386052815128100865/386054223688630272/1012209896726478868): modpack is e6e 1.4.1

**Comment by rubensworks** [comment]
@kirjorjos Do you know if those items use any special kind of NBT data?
And if so, could you share this NBT information here?

**Comment by kirjorjos** [comment]
The occultism books say 1 nbt tag but come up blank attempting to read it with "slot item" from an inventory reader > item nbt > display panel.  The same thing applies for the astral gateway.

**Comment by kirjorjos** [comment]
Upon further testing, it works as expected locally and breaks on servers.

**Comment by rubensworks** [comment]
Can you check what happens in a pack with just the mods mentioned above? Could also be related to some other mod, or perhaps some config option in the server.

**Comment by kirjorjos** [comment]
I had tested it with the mods listed above on a comment Natalie made, it works as expected locally, I did not try on a server with the mods as it was working locally, but seeing as it only breaks in the server with e6e, I'll try it in a server with the mods mentioned above.

**Comment by kirjorjos** [comment]
It works as expected on a localhost server with the mods mentioned above.  I don't have a non-localhost server to test it with, but I imagine it wouldn't mater.

**Comment by rubensworks** [comment]
Thanks for checking. In that case there's some other mod in the pack messing with things, or there's some config option on your server that breaks things. I suggest taking this up with your modpack author or server owner.
If there's any new information that would come in, be sure to report this here, and we can re-open this issue if needed.

Since the JEI integration works, while the clicking doesn't, I suspect there's some client-side mod in your pack blocking things somehow.

(Another question that may be relevant: does shift-clicking the item out of your terminal work?)
