### ISSUE TITLE
Issue closed

### ISSUE THREAD

**Issue by GuivinALT** [CyclopsMC/IntegratedTerminals#88]
Issue closed

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by GuivinALT** [comment]
> 

You're welcome, sorry for the mean language implied.

**Comment by rubensworks** [comment]
> If this problem only occurs in combination with other mods, attempt to find the smallest set of mods that causes the problem.
--> No :D

What does that mean?
That it doesn't occur with other mods?
Or that you didn't test it?

**Comment by sctjkc01** [comment]
I have reproduced this issue with the following mods/versions:

- Minecraft: 1.18.2
- Forge: 40.1.74
- Common Capabilities version 1.18.2-2.8.2
- Cyclops Core version 1.18.2-1.16.0
- **Integrated Terminals** version 1.18.2-1.3.1
- Integrated Crafting version 1.18.2-1.0.25
- Integrated Dynamics version 1.18.2-1.11.12
- Integrated Tunnels version 1.18.2-1.8.15

This issue is not specific to NTC2, nor is it specific to 1.16.5.

**Comment by rubensworks** [comment]
Thanks for checking!

**Comment by sctjkc01** [comment]
I have also separately confirmed that this is specific to the Portable Storage Terminal; the static one that is placed on a cable is not afflicted by this duplication bug.  Perhaps the Portable Storage Terminal has an internal inventory that isn't being cleared?

**Comment by sctjkc01** [comment]
Well, this about confirms that theory:
![image](https://user-images.githubusercontent.com/1090204/190984815-0826e86e-ba38-4b52-81af-4b8834e47342.png)
Making use of an Entity Reader and watching the NBT of the Portable Storage Terminal (namely `integratedterminals:namedInventories/minecraft:itemstack_crafting/Items`) in the first slot of my inventory, I spotted that the internal inventory is not being cleared after shift-clicking that button.

Without the ability to step through with a debugger, I can only offer that the issue lies somewhere within `TerminalStorageIngredientItemStackCraftingGridClear.clearGrid`.  Though I can just now theorize that perhaps the crafting inventory does not have a flushing update at the end of the clearing session... clearing to storage still [writes back an empty slot on a successful slot emptying](https://github.com/CyclopsMC/IntegratedTerminals/blob/release-1.18/src/main/java/org/cyclops/integratedterminals/network/packet/TerminalStorageIngredientItemStackCraftingGridClear.java#L77) but no such "dirty-marking write" occurs in the event of a clear to the player's inventory.  🤔

**Comment by GuivinALT** [comment]
> > If this problem only occurs in combination with other mods, attempt to find the smallest set of mods that causes the problem.
> > --> No :D
> 
> What does that mean? That it doesn't occur with other mods? Or that you didn't test it?

I didn't test, but you got the answer from sctjkc01 :)
I was very very tired, haven't slept for 30 hours so pardon me for the imprecisions.

**Comment by rubensworks** [comment]
@GuivinALT Does this

**Comment by sctjkc01** [comment]
Is this issue closed?  It appears to still exist as of Integrated Terminals 1.18.2-1.3.2.

( for reference, this issue was a duplication bug stemming from shift-clicking the "clear crafting grid" button in the Portable Storage Terminal; it does not actually empty out the grid's inventory on the server when clicking the button - it clears client-side, but closing and re-opening the terminal shows a tangible copy of what was previously there )

**Comment by rubensworks** [comment]
@sctjkc01 Could you create a new issue for it?
